### ISSUE TITLE
ThreadLocal.py to support settings.MIDDLEWARE

### ISSUE THREAD

**Issue by thefon** [jedie/django-tools#12]
as per
https://docs.djangoproject.com/en/1.11/topics/http/middleware/#upgrading-middleware

ThreadLocal should inherit from django.utils.deprecation.MiddlewareMixin

**Comment by jedie** [comment]
pull request are welcome ;)

**Comment by thefon** [comment]
Knew you'd say that!  :)
I'll look at it if I can, but it will take me longer to set up a dev / test environment.
