### ISSUE TITLE
LICENSE permissive?

### ISSUE THREAD

**Issue by tony** [jedie/django-tools#14]
I have nothing wrong with GPL, but users probably don't want to have their website or libraries pulling in django-tools becoming a derivative of it.  Can you release this under a permissive license like ISC, MIT, BSD, Apache 2, etc?

**Comment by jedie** [comment]
no i love GPL ;)

**Comment by tony** [comment]
I didn't end up using this due to the license. I forgot the original thing I was looking for at the time.

**Comment by jedie** [comment]
no problem
