### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [jedie/django-tools#15]
![DJTOOLS](https://user-images.githubusercontent.com/36298335/55352723-852ce000-54e7-11e9-89dd-2c7ae6d6aeb8.jpg)

Hello @jedie I contribute to open source softwares by designing logos.  I designed a functional logo for this repo. It will look like this in the readme file : 

![dj2](https://user-images.githubusercontent.com/36298335/55352709-7fcf9580-54e7-11e9-96c1-d3082d00697e.png)

 What do you think about the logo?

**Comment by jedie** [comment]
Nice! Thanks for contributing.

Think the second one is the best... I have a suggestion:

What if "django" is still readable? So the "d" and the "j" as a tool, but not crosswise and then "ango-tool" normally at the end.

**Comment by reallinfo** [comment]
Oh, Thanks for suggestion but the letters(on tool form) are too cramped when they are vertical. That's why I found a new idea. 

![dj1](https://user-images.githubusercontent.com/36298335/55387419-70883080-5557-11e9-84db-0c8b2daa94f3.jpg)

I think it is more readable, simpler, more functional version.  because '' dj '' represents django. it also takes up less space. so the ''tools'' become more visible. What do you think?

![dj2](https://user-images.githubusercontent.com/36298335/55387527-98779400-5557-11e9-80a9-1fb285d3c8e0.jpg)

**Comment by jedie** [comment]
Wow, that's cool:

![grafik](https://user-images.githubusercontent.com/71315/55407688-b7c5ef80-555e-11e9-9b2b-628317db21e0.png)

**Comment by reallinfo** [comment]
Oh okay. I can send source files if you don't have another request. (Pull request)

**Comment by jedie** [comment]
I am happy ;)

**Comment by reallinfo** [comment]
i sent a pr. https://github.com/jedie/django-tools/pull/16

I was going to put the logo in the readme file, but there was a problem.
